name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Delete Docker Image and Containers
        run: |
          sudo docker ps -q --filter "name=dweb" | xargs -r sudo docker stop
          sudo docker ps -aq --filter "name=dweb" | xargs -r sudo docker rm
          sudo docker images -q dweblab/songdo:latest | xargs -r sudo docker rmi

      - name: Pull Docker Image from Docker Hub
        run: sudo docker pull dweblab/songdo:latest

      - name: Execute Docker Container
        run: |
          sudo docker run -d -p 80:3000 --name dweb dweblab/songdo:latest
